In [1]:
def add_number(x,y,z=None,flag=True):
    if(flag==False):
        print('Flag is False')
    else:
        print('Flag is True')
        
    if(z==None):
        return x+y
    else:
        return x+y+z
    
print(add_number(1,2,flag=False))

Flag is False
3


In [3]:
def add_number(x,y):
    return x+y

a= add_number
a(1,2)

3

In [4]:
type('This is a string')

str

In [5]:
type(add_number)

function

In [7]:
#Tuples are an immutable data structure (cannot be altered).

x= (1,'a',2,'b')
type(x)

tuple

In [8]:
#Lists are a mutable data structure.

x=[1,'a',2,'b']
type(x)

list

In [9]:
#Use append to append an object to a list.

x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [10]:
# loop

for item in x:
    print(item)

1
a
2
b
3.3


In [13]:
# loop using the indexing operator

i=0
while(i!=len(x)):
      print(x[i])
      i=i+1

1
a
2
b
3.3


In [14]:
# Use + to concatenate lists.

[1,2]+[3.4,5.6]

[1, 2, 3.4, 5.6]

In [15]:
# Use * to repeat lists.

[1]*3

[1, 1, 1]

In [16]:
# Use the in operator to check if something is inside a list.

1 in [1,2,3]

True

In [23]:
# Now let's look at strings. Use bracket notation to slice a string.

x = 'This is string'
print(x[0])
print(x[0:3])
print(x[-1])
print(x[-3])
print(x[-4:-2])
print(x[:3])

T
Thi
g
i
ri
Thi


In [28]:
firstname = 'Ankur'
lastname = 'singh'

print(firstname+' '+lastname)
print(firstname*3)
print('Ankur' in firstname)

Ankur singh
AnkurAnkurAnkur
True


In [31]:
# Split returns a list of all the words in a string, or a list split on a specific character.

firstname = 'Ankur Atul Nidhi'.split(' ')
lastname = 'Singh Kumar Rajput'.split(' ')

print(firstname)
print(lastname)

['Ankur', 'Atul', 'Nidhi']
['Singh', 'Kumar', 'Rajput']


In [32]:
# Make sure you convert objects to strings before concatenating.

'Ankur'+str(31)

'Ankur31'

In [39]:
#Dictionaries associate keys with values.

x = {'Ankur':'ankur310794@gmail.com','Atul':'atul@gmail.com'}
print(x['Ankur'])

# Iterate over all of the keys:

for name in x:
    print(x[name])

# Iterate over all of the values:

for email in x.values():
    print(email)
    
# Iterate over all of the items in the list:

for name,email in x.items():
    print(name+':'+email)
    
    


ankur310794@gmail.com
atul@gmail.com
ankur310794@gmail.com
atul@gmail.com
ankur310794@gmail.com
Atul:atul@gmail.com
Ankur:ankur310794@gmail.com


In [41]:
# You can unpack a sequence into different variables:

x = ('Ankur','ankur@gmail.com',str(310794))
name,email,eid=x
print(name+' '+email+' '+eid)

Ankur ankur@gmail.com 310794


In [42]:
# Python has a built in method for convenient string formatting.

sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                            sales_record['num_items'],
                            sales_record['price'],
                            sales_record['num_items']*sales_record['price']))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


In [63]:
# Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

import csv
%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

mpg[:3]

[{'': '1',
  'class': 'compact',
  'cty': '18',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'auto(l5)',
  'year': '1999'},
 {'': '2',
  'class': 'compact',
  'cty': '21',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m5)',
  'year': '1999'},
 {'': '3',
  'class': 'compact',
  'cty': '20',
  'cyl': '4',
  'displ': '2',
  'drv': 'f',
  'fl': 'p',
  'hwy': '31',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m6)',
  'year': '2008'}]

In [64]:
# len shows that our list is comprised of 234 dictionaries

len(mpg)

234

In [66]:
# find the average cty fuel economy across all cars

sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [67]:
# find the average hwy fuel economy across all cars.

sum(float(d['hwy']) for d in mpg)/len(mpg)

23.44

In [69]:
# set to return the unique values for the number of cylinders the cars in our dataset have

cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [72]:
# grouping the cars by number of cylinder, and finding the average cty mpg for each group.

CtyMpgByCyl = []

for c in cylinders:
    summpg = 0
    cyltypecount =0
    
    for d in mpg:
        if d['cyl']==c:
            summpg+= float(d['cty'])
            cyltypecount += 1
    CtyMpgByCyl.append((c,summpg/cyltypecount))
    
CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl
            

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [73]:
# Use set to return the unique values for the class types in our dataset.

vehicleclass = set(d['class'] for d in mpg)

vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [74]:
# find the average hwy mpg for each class of vehicle in our dataset

HwyMpgByClass = []

for t in vehicleclass:
    summpg=0
    vclasscount=0
    
    for d in mpg:
        if d['class']==t:
            summpg+= float(d['hwy'])
            vclasscount+=1
    HwyMpgByClass.append((t,summpg/vclasscount))
    
HwyMpgByClass.sort(key=lambda x:x[1])

HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

In [75]:
import datetime as dt
import time as tm

In [76]:
tm.time()

1485188878.54

In [77]:
# Convert the timestamp to datetime.

dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2017, 1, 23, 16, 29, 4, 854030)

In [79]:
# Class 

class Person:
    dept = 'CSE'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location
        
person = Person()
person.set_name('Ankur')
person.set_location('GKP')

print('{} live in {} and works in {} department'.format(person.name,person.location,person.dept))


Ankur live in GKP and works in CSE department


In [84]:
store1 = [10.00,11.00,12.34,2.34]
store2 = [9.00,11.10,12.34,2.01]

cheapest = map(min,store1,store2)
cheapest

In [85]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In [96]:
# example of lambda that takes in three parameters and adds the first two

my_function = lambda a,b,c:a+b
my_function(1,2,3)

3

In [98]:
# iterate from 0 to 999 and return the even numbers.

my_list = []
for number in range(0,100):
    if number%2==0:
        my_list.append(number)
        
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [99]:
#  same thing but with list comprehension.

my_list = [number for number in range(0,100) if number%2==0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [101]:
# The Python Programming Language: Numerical Python 

import numpy as np

In [102]:
# Create a list and convert it to a numpy array

mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [103]:
# Pass in a list of lists to create a multidimensional array.

m  = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
# Use the shape method to find the dimensions of the array

m.shape

(2, 3)

In [106]:
# arange returns evenly spaced values within a given interval.

n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [107]:
# reshape returns an array with the same data with a new shape.

n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [110]:
# linspace returns evenly spaced numbers over a specified interval.

o = np.linspace(0,5,9)
o

array([ 0.  ,  0.62,  1.25,  1.88,  2.5 ,  3.12,  3.75,  4.38,  5.  ])

In [111]:
# resize changes the shape and size of array in-place.

o.resize(3,3)
o

array([[ 0.  ,  0.62,  1.25],
       [ 1.88,  2.5 ,  3.12],
       [ 3.75,  4.38,  5.  ]])

In [114]:
# ones returns a new array of given shape and type, filled with ones.

np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [115]:
# zeros returns a new array of given shape and type, filled with zeros.

np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [116]:
# eye returns a 2-D array with ones on the diagonal and zeros elsewhere.

np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [117]:
#diag extracts a diagonal or constructs a diagonal array.

y = [1,2,3]
np.diag(y)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [118]:
# Create an array using repeating list (or see np.tile)

np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [119]:
# Repeat elements of an array using repeat.

np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [128]:
# Combining Arrays

p = np.ones([2,3],int)
p


array([[1, 1, 1],
       [1, 1, 1]])

In [130]:
#Use vstack to stack arrays in sequence vertically (row wise).

x = np.vstack([p,2*p])
x

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [131]:
# Use hstack to stack arrays in sequence horizontally (column wise).

y = np.hstack([p,2*p])
y

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [153]:
# Use +, -, *, / and ** to perform element wise addition, subtraction, multiplication, division and power.

x = np.array([1,2,3])
y = np.array([4,5,6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

print('dot product:')
print(x.dot(y))

print(x**2)

z = np.array([x,y])
z.T

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[ 0.25  0.4   0.5 ]
dot product:
32
[1 4 9]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [156]:
# Math Functions
# Numpy has many built in math functions that can be performed on arrays

a = np.array([-4, -2, 1, 3, 5])

print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.argmax())
print(a.argmin())

3
-4
5
0.6
3.26190128606
4
0


In [ ]:
# Indexing / Slicing

